/* SEGA Saturn main program for Hatch Game Engine exports
 *
 * Generated by the Hatch Game Engine's SEGA Saturn exporter.
 * The scene's art is in res/, already converted for the Saturn VDP.
 */

#include "saturn.h"

extern const unsigned char scene_image[];
extern const unsigned short scene_palette[];

static int cameraX = 0;
static int cameraY = 0;

int main(void) {
    /* Initialize Saturn hardware */
    /* TODO: Add proper Saturn initialization with SDK */
    
    /* Load palette into CRAM */
    /* TODO: Use Saturn SDK functions to load palette */
    
    /* Main loop */
    while (1) {
        /* Read controller input */
        /* TODO: Use Saturn SDK to read pad input */
        
        /* Update camera position based on input */
        /* if (pad & BUTTON_RIGHT) cameraX += 4; */
        /* if (pad & BUTTON_LEFT)  cameraX -= 4; */
        /* if (pad & BUTTON_DOWN)  cameraY += 4; */
        /* if (pad & BUTTON_UP)    cameraY -= 4; */
        
        /* Blit visible portion of image to framebuffer */
        /* TODO: Use Saturn SDK blitting functions */
        
        /* Wait for VBLANK */
        /* TODO: Use Saturn SDK VBLANK wait */
    }
    
    return 0;
}
